apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  namespace: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: maylatt/myapi:3.0.0
        env:
          - name: REDIS_HOST
            value: redis-svc.site.svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
