apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: site
spec:
  selector:
    matchLabels:
      app: redis-cluster
  serviceName: redis-svc
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:7.0.7-alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: bus
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: data
          mountPath: /data
      volumes:
        - name: conf
          configMap:
            name: redis-cluster
            defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
