apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
