apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapi
  namespace: site
  labels:
    app: myapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
        - name: myapi
          image: maylatt/myapi:2.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8000      
    
