name: Test on PR and Push

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  
jobs:
  test:
    name: Test on PR and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r utils/requirements.txt
    
    - name: Run Python tests
      run: |
        python $(ls -t $(find . -name "*.py") | head -1)

  approve:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Approval
        uses: "peter-evans/create-pull-request@v3.9.0"
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          commit-message: "Auto-approve"
          title: "Auto-approve"
          body: "Auto-approve"
          branch: auto-approve
          delete-branch: true
          labels: "approved"