name: Test on PR and Push

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  
jobs:
  test:
    name: Test on PR and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r utils/requirements.txt
    
    - name: Run Python tests
      run: |
        python $(ls -t $(find . -name "*.py") | head -1)